#!/usr/bin/env python

import sys
sys.path.insert(0, '..')

import util.gst as gst

# Don't commit (yet), just a simple helper script to convert data with GST to
# unixtimestampped data

def main():
    file = sys.argv[1]
    f = open(file, 'r')
    for line in f:
        t = line.rstrip().split(" ")
        wn = int(t[0])
        tow = int(t[1])
        fields = t[2:]
        ts = gst.gst2timestamp(wn, tow)
        fields.insert(0, str(ts))
        print(" ".join(fields))


if __name__ == "__main__":
    main()
