%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Copyright 2015-2026 Finnish Geospatial Research Institute FGI, National
%% Land Survey of Finland. This file is part of FGI-GSRx software-defined
%% receiver. FGI-GSRx is a free software: you can redistribute it and/or
%% modify it under the terms of the GNU General Public License as published
%% by the Free Software Foundation, either version 3 of the License, or any
%% later version. FGI-GSRx software receiver is distributed in the hope
%% that it will be useful, but WITHOUT ANY WARRANTY, without even the
%% implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
%% See the GNU General Public License for more details. You should have
%% received a copy of the GNU General Public License along with FGI-GSRx
%% software-defined receiver. If not, please visit the following website 
%% for further information: https://www.gnu.org/licenses/
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function tC = gpsl1setTrackingTable(tC, trackState)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Initialises tracking table for gps signals
%
% Inputs:
%   tC          - Results from signal tracking for one channel
%   trackState  - Tracking state of channel
%
% Outputs:
%   tC          - Results from signal tracking for one channel
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if length(tC.codeReplica)/1023 == 20
    epochInterval = 20;
    frequencyDiscriminator = 'freqDiscrimAtan';
else
    epochInterval = 1;
    frequencyDiscriminator = 'freqDiscrimAtan2';
end
% Set functions to be executed for each defined mode
switch(trackState)    
    case 'STATE_PULL_IN'
        tC.trackTable =...
            {'CN0fromSNR',epochInterval;...            
            frequencyDiscriminator,epochInterval;...
            'freqLoopFilterWide',epochInterval;...            
            'phaseDiscrim',epochInterval;...
            'phaseLoopFilterWide',epochInterval;...
            'bitSync',20;...
            'phaseFreqFilter',epochInterval;...
            'codeDiscrim',epochInterval,;...
            'codeLoopFilter',epochInterval;...
            'lockDetect',epochInterval;...
            'gpsl1UpdateChannelState',epochInterval};
case 'STATE_COARSE_TRACKING'
        tC.trackTable =...
            {'CN0fromSNR',epochInterval;...            
            frequencyDiscriminator,epochInterval;...
            'freqLoopFilterNarrow',epochInterval;...            
            'phaseDiscrim',epochInterval;...
            'phaseLoopFilterNarrow',epochInterval;...
            'bitSync',20;...
            'phaseFreqFilter',epochInterval;...            
            'codeDiscrim',epochInterval,;...
            'codeLoopFilter',epochInterval;...
            'lockDetect',epochInterval;...
            'gpsl1UpdateChannelState',epochInterval};        
    case 'STATE_FINE_TRACKING'
        tC.trackTable =...
            {'CN0fromSNR',epochInterval;...                        
            frequencyDiscriminator,epochInterval;...
            'freqLoopFilterVeryNarrow',epochInterval;...            
            'phaseDiscrim',epochInterval;...
            'phaseLoopFilterVeryNarrow',epochInterval;...
            'bitSync',20;...
            'phaseFreqFilter',epochInterval;...            
            'codeDiscrim',epochInterval,;...
            'codeLoopFilter',epochInterval;...
            'lockDetect',epochInterval;...
            'gpsl1UpdateChannelState',epochInterval};
end








