%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Copyright 2015-2021 Finnish Geospatial Research Institute FGI, National
%% Land Survey of Finland. This file is part of FGI-GSRx software-defined
%% receiver. FGI-GSRx is a free software: you can redistribute it and/or
%% modify it under the terms of the GNU General Public License as published
%% by the Free Software Foundation, either version 3 of the License, or any
%% later version. FGI-GSRx software receiver is distributed in the hope
%% that it will be useful, but WITHOUT ANY WARRANTY, without even the
%% implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
%% See the GNU General Public License for more details. You should have
%% received a copy of the GNU General Public License along with FGI-GSRx
%% software-defined receiver. If not, please visit the following website 
%% for further information: https://www.gnu.org/licenses/
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [obsCh] = doOSNMAUpdate(obsCh, OSNMA_tab,flag_kroot)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Function updates observations with OSNMA verifications for each PRN. 
% The information is saved in a structure format with information about 
% multiple tags  generated by doOSNMAAnalysis function 
%
% Inputs:
%   obsCh               - Observations for one channel
%   OSNMA_tab           - OSNMA information table
%   flag_kroot          - Hot start flag 

%
% Outputs:
%   obsCh               - Observations for one channel
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if(flag_kroot==0)
          disp('OSNMA Receiver initialization incomplete, Data may be too short');
           for i=1:length(obsCh.channel)
               obsCh.channel(i).OSNMA.OSNMAEnable=0;
               obsCh.channel(i).OSNMA.time_lapse=0;
               obsCh.channel(i).OSNMA.SlowMACSelfAuthentication=0;   % Case 1: Slow MAC self-authentication (ADKD 12)
                obsCh.channel(i).OSNMA.SlowMACCrossAuthentication=0; % Case 2: Slow MAC cross-authentication (ADKD 12)
                obsCh.channel(i).OSNMA.AuthenticationSelf=0;         % Case 3: Satellite authenticated itself (ADKD 0)
                obsCh.channel(i).OSNMA.CrossAuthentication=0;        % Case 4: Cross authenticated (ADKD 0)
                obsCh.channel(i).OSNMA.GalTiminingAuthentication=0;  % Case 5: Galileo timing authentication (ADKD 4)
                obsCh.channel(i).OSNMA.AuthenticationFailed_ADKD0=0; % Case 6: Authentication failed (ADKD 0)
                obsCh.channel(i).OSNMA.GapSubframe=0;                % Case 7: Gap in subframe
                obsCh.channel(i).OSNMA.TESLAKeyVerficationFailed=0;  % Case 8: Page with failed CRC
                obsCh.channel(i).OSNMA.AllZero=0;                    % Case 9: All OSNMA bits in a frame are zero
                obsCh.channel(i).OSNMA.TagFail=0;                    % Case 10: Tag fail: Not Authenticated           
                obsCh.channel(i).OSNMA.InsufficientADKD0=0;          % Case 11: Authentication not possible: insufficient data with ADKD0 failiures
                obsCh.channel(i).OSNMA.MissingNAVData=0;             % Case 12: Missing NAVDATA with multiple ADKD values
                obsCh.channel(i).OSNMA.CRCFailed=0;                  % Case 13: CRC Fail
           end
else
j=1;
    for i=1:length(obsCh.channel)  
        if(j<=length(OSNMA_tab)) 
             if(find(obsCh.channel(i).SvId.satId==OSNMA_tab(j).svID))  %Check if OSNMA Hex was not generated for a satellite
                obsCh.channel(i).OSNMA.OSNMAEnable=1;
                obsCh.channel(i).OSNMA.time_lapse=OSNMA_tab(j).time_lapse;
                obsCh.channel(i).OSNMA.SlowMACSelfAuthentication=OSNMA_tab(j).authentic_time(1,:);  % Case 1: Slow MAC self-authentication (ADKD 12)
                obsCh.channel(i).OSNMA.SlowMACCrossAuthentication=OSNMA_tab(j).authentic_time(2,:); % Case 2: Slow MAC cross-authentication (ADKD 12)
                obsCh.channel(i).OSNMA.AuthenticationSelf=OSNMA_tab(j).authentic_time(3,:);         % Case 3: Satellite authenticated itself (ADKD 0)
                obsCh.channel(i).OSNMA.CrossAuthentication=OSNMA_tab(j).authentic_time(4,:);        % Case 4: Cross authenticated (ADKD 0)
                obsCh.channel(i).OSNMA.GalTiminingAuthentication=OSNMA_tab(j).authentic_time(5,:);  % Case 5: Galileo timing authentication (ADKD 4)
                obsCh.channel(i).OSNMA.AuthenticationFailed_ADKD0=OSNMA_tab(j).authentic_time(6,:); % Case 6: Authentication failed (ADKD 0)
                obsCh.channel(i).OSNMA.GapSubframe=OSNMA_tab(j).authentic_time(7,:);                % Case 7: Gap in subframe
                obsCh.channel(i).OSNMA.TESLAKeyVerficationFailed=OSNMA_tab(j).authentic_time(8,:);  % Case 8: TESLA key verification fail
                obsCh.channel(i).OSNMA.AllZero=OSNMA_tab(j).authentic_time(9,:);                    % Case 9: All OSNMA bits in a frame are zero
                obsCh.channel(i).OSNMA.TagFail=OSNMA_tab(j).authentic_time(10,:);                   % Case 10: Tag fail: Not Authenticated
                obsCh.channel(i).OSNMA.InsufficientADKD0=OSNMA_tab(j).authentic_time(11,:);         % Case 11: Authentication not possible: insufficient data with ADKD0 failiures
                obsCh.channel(i).OSNMA.MissingNAVData=OSNMA_tab(j).authentic_time(12,:);            % Case 12: Missing NAVDATA with multiple ADKD values
                obsCh.channel(i).OSNMA.CRCFailed=OSNMA_tab(j).authentic_time(13,:);                 % Case 13: CRC Fail
                j=j+1;
             else
               obsCh.channel(i).OSNMA.OSNMAEnable=0;
               obsCh.channel(i).OSNMA.time_lapse=0;
               obsCh.channel(i).OSNMA.SlowMACSelfAuthentication=0; % Case 1: Slow MAC self-authentication (ADKD 12)
               obsCh.channel(i).OSNMA.SlowMACCrossAuthentication=0; % Case 2: Slow MAC cross-authentication (ADKD 12)
               obsCh.channel(i).OSNMA.AuthenticationSelf=0;         % Case 3: Satellite authenticated itself (ADKD 0)
               obsCh.channel(i).OSNMA.CrossAuthentication=0;       % Case 4: Cross authenticated (ADKD 0)
               obsCh.channel(i).OSNMA.GalTiminingAuthentication=0;  % Case 5: Galileo timing authentication (ADKD 4)
               obsCh.channel(i).OSNMA.AuthenticationFailed_ADKD0=0; % Case 6: Authentication failed (ADKD 0)
               obsCh.channel(i).OSNMA.GapSubframe=0;                % Case 7: Gap in subframe
               obsCh.channel(i).OSNMA.TESLAKeyVerficationFailed=0;  % Case 8: Page with failed CRC
               obsCh.channel(i).OSNMA.AllZero=0;                    % Case 9: All OSNMA bits in a frame are zero
               obsCh.channel(i).OSNMA.TagFail=0;                    % Case 10: Tag fail: Not Authenticated           
               obsCh.channel(i).OSNMA.InsufficientADKD0=0;          % Case 11: Authentication not possible: insufficient data with ADKD0 failiures
               obsCh.channel(i).OSNMA.MissingNAVData=0;             % Case 12: Missing NAVDATA with multiple ADKD values
               obsCh.channel(i).OSNMA.CRCFailed=0;                  % Case 13: CRC Fail
             end
        else
               obsCh.channel(i).OSNMA.OSNMAEnable=0;
               obsCh.channel(i).OSNMA.time_lapse=0;
               obsCh.channel(i).OSNMA.SlowMACSelfAuthentication=0;  % Case 1: Slow MAC self-authentication (ADKD 12)
               obsCh.channel(i).OSNMA.SlowMACCrossAuthentication=0; % Case 2: Slow MAC cross-authentication (ADKD 12)
               obsCh.channel(i).OSNMA.AuthenticationSelf=0;         % Case 3: Satellite authenticated itself (ADKD 0)
               obsCh.channel(i).OSNMA.CrossAuthentication=0;        % Case 4: Cross authenticated (ADKD 0)
               obsCh.channel(i).OSNMA.GalTiminingAuthentication=0;  % Case 5: Galileo timing authentication (ADKD 4)
               obsCh.channel(i).OSNMA.AuthenticationFailed_ADKD0=0; % Case 6: Authentication failed (ADKD 0)
               obsCh.channel(i).OSNMA.GapSubframe=0;                % Case 7: Gap in subframe
               obsCh.channel(i).OSNMA.TESLAKeyVerficationFailed=0;  % Case 8: Page with failed CRC
               obsCh.channel(i).OSNMA.AllZero=0;                    % Case 9: All OSNMA bits in a frame are zero
               obsCh.channel(i).OSNMA.TagFail=0;                    % Case 10: Tag fail: Not Authenticated           
               obsCh.channel(i).OSNMA.InsufficientADKD0=0;          % Case 11: Authentication not possible: insufficient data with ADKD0 failiures
               obsCh.channel(i).OSNMA.MissingNAVData=0;             % Case 12: Missing NAVDATA with multiple ADKD values
               obsCh.channel(i).OSNMA.CRCFailed=0;                  % Case 13: CRC Fail 
        end

    end
end
