%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Copyright 2015-2021 Finnish Geospatial Research Institute FGI, National
%% Land Survey of Finland. This file is part of FGI-GSRx software-defined
%% receiver. FGI-GSRx is a free software: you can redistribute it and/or
%% modify it under the terms of the GNU General Public License as published
%% by the Free Software Foundation, either version 3 of the License, or any
%% later version. FGI-GSRx software receiver is distributed in the hope
%% that it will be useful, but WITHOUT ANY WARRANTY, without even the
%% implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
%% See the GNU General Public License for more details. You should have
%% received a copy of the GNU General Public License along with FGI-GSRx
%% software-defined receiver. If not, please visit the following website 
%% for further information: https://www.gnu.org/licenses/
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [GalOsnma, flag_kroot] = doOSNMAAnalysis(fileID,flag_kroot)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This function reads the output file generated by FGI-OSNMA and converts
% it into a readable format for interface with the reciever. It generates  
% an analysis of OSNMA performance over the complete
% time span of simulation
%
% Inputs:
%   fileID          - Detail output file from FGI-OSNMA Python package 
%   flag_kroot      - flag to indicate if the KROOT is provided by the user
%
% Outputs           - Detailed validated OSNMA data
%   GalOsnma        - Detail output file from FGI-OSNMA Python package 
%   flag_kroot      - flag to indicate if the KROOT is provided by the user
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Case 1: Slow MAC self-authentication (ADKD 12)
        % Case 2: Slow MAC cross-authentication (ADKD 12)
        % Case 3: Satellite authenticated itself (ADKD 0)
        % Case 4: Cross authenticated (ADKD 0)
        % Case 5: Galileo timing authentication (ADKD 4)
        % Case 6: ADKD0 authentication Fail
        % Case 7: Gap in subframe
        % Case 8: TESLA key verification fails
        % Case 9: All OSNMA bits in a frame are zero
        % Case 10:Tag fail: Not Authenticated
        % Case 11: Authentication not possible: insufficient data 
        % with ADKD0 failures
        % Case 12: Missing NAVDATA with multiple ADKD values
        % Case 13: CRC Fail
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Note: Only features relvant to the receiver are displayed. The user has
%the option to see multiple other scenarios listed as cases above by
%uncommenting the relevant section in the plots.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if(flag_kroot==0)
    fid = fopen(fileID);
    tline = fgetl(fid);
    while ischar(tline)
        tline = fgetl(fid);
        if(strcmp(tline,'DSM message of type DsmMessageType.kroot completed'))
            flag_kroot=1; break;
        end
    end
fclose(fid);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Checking if kroot is initialized
if(flag_kroot==0) 
    disp('OSNMA Receiver initialization incomplete, Data may be too short');
    GalOsnma.Authentication = 0;
else
    disp('OSNMA Receiver initialization complete');
     
    Osnma_tab = table; %(SVID,PRNA,WN,TOW,ADKD,Outcome,Gap,AllZeros,TESLAfail,Tagfail);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

   %Collecting data for Incomplete subframe, TESLA fails, all zeros OSNMA msg and subfram gaps
    fid = fopen(fileID);
    tline = fgetl(fid);
    %j=1;
    while ischar(tline)
        tline = fgetl(fid);
           
        if(strfind(tline,'INCOMPLETE_SUBFRAME'))
            t_hold=str2double(extract(tline, digitsPattern));
            Temp = cell2table({t_hold(3) NaN t_hold(1) t_hold(2) 99 NaN 1 0 0 0 0},'VariableNames',{'SVID','PRNA','WN','TOW','ADKD','Outcome','Gap','AllZeros','TESLAfail','Tagfail','CRC'});
            Osnma_tab=[Osnma_tab ;Temp];       
        end

        if(strfind(tline,'CRC_ERROR'))
            t_hold=str2double(extract(tline, digitsPattern));
            Temp = cell2table({t_hold(3) NaN t_hold(1) t_hold(2) 99 NaN 0 0 0 0 1},'VariableNames',{'SVID','PRNA','WN','TOW','ADKD','Outcome','Gap','AllZeros','TESLAfail','Tagfail','CRC'});
            Osnma_tab=[Osnma_tab ;Temp];       
        end

        if(strfind(tline,'NO_OSNMA_BITS'))
            t_hold=str2double(extract(tline, digitsPattern));
            Temp = cell2table({t_hold(3) NaN t_hold(1) t_hold(2) 99 NaN 0 1 0 0 0},'VariableNames',{'SVID','PRNA','WN','TOW','ADKD','Outcome','Gap','AllZeros','TESLAfail','Tagfail','CRC'});
            Osnma_tab=[Osnma_tab ;Temp];       
        end

        if(strfind(tline,'TESLA_KEY_VERIFICATION_FAILED'))
            t_hold=str2double(extract(tline, digitsPattern));
            Temp = cell2table({t_hold(3) NaN t_hold(1) t_hold(2) 99 NaN 0 0 1 0 0},'VariableNames',{'SVID','PRNA','WN','TOW','ADKD','Outcome','Gap','AllZeros','TESLAfail','Tagfail','CRC'});
            Osnma_tab=[Osnma_tab ;Temp];      
        end

        if(strfind(tline,'TAG_SEQUENCE_VERIFICATION_FAILED'))
            t_hold=str2double(extract(tline, digitsPattern));
            Temp = cell2table({t_hold(3) NaN t_hold(1) t_hold(2) 99 NaN 0 0 0 1 0},'VariableNames',{'SVID','PRNA','WN','TOW','ADKD','Outcome','Gap','AllZeros','TESLAfail','Tagfail','CRC'});
            Osnma_tab=[Osnma_tab ;Temp];      
        end
        

        if(strfind(tline,'NAV_AUTH_EVENT'))
            t_hold=str2double(extract(tline, digitsPattern));
            if(strfind(tline,'AUTH_OK'))
                t_hold(6)=1;
            if(t_hold(3)==255)
                t_hold(3)=t_hold(4);
            end
            
            Temp = cell2table({t_hold(3) t_hold(4) t_hold(1) t_hold(2) t_hold(5) t_hold(6) 0 0 0 0 0},'VariableNames',{'SVID','PRNA','WN','TOW','ADKD','Outcome','Gap','AllZeros','TESLAfail','Tagfail','CRC'});
            Osnma_tab=[Osnma_tab ;Temp];    
            end
        end
    end
    fclose(fid);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  %Generating a list unique staellites
    sat_ID=unique(Osnma_tab.SVID);
    sat_ID=sat_ID(~isnan(sat_ID));
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  
%    
Sort=sortrows(Osnma_tab,1);
    for i=1:length(sat_ID)
        GalOsnma(i).svID=sat_ID(i);
        c = ismember(Sort.SVID,sat_ID(i));
        GalOsnma(i).data=Sort(min(find(c)):max(find(c)),:);
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        GalOsnma(i).time_lapse=min(unique(Osnma_tab.TOW)):max(unique(Osnma_tab.TOW));
        GalOsnma(i).authentic_time=ones(13,length(GalOsnma(i).time_lapse))*nan; %Initializing timelines for multiple test cases    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

        for j=1:length(GalOsnma(i).time_lapse)
             ind=find(GalOsnma(i).data.TOW==GalOsnma(i).time_lapse(j));       
            if(ind>0)
                for k=1:length(ind)
                    
                    switch GalOsnma(i).data.ADKD(ind(k))
                        case 0
                            if(GalOsnma(i).data.Outcome(ind(k))<12)&&(GalOsnma(i).data.Outcome(ind(k))>0)
                                if(GalOsnma(i).data.SVID(ind(k))==GalOsnma(i).data.PRNA(ind(k)))
                                    GalOsnma(i).authentic_time(3,j)= GalOsnma(i).data.SVID(ind(k)); %Satellite authenticated itself (ADKD 0)
                                else
                                    GalOsnma(i).authentic_time(4,j)= GalOsnma(i).data.SVID(ind(k)); %Cross authenticated (ADKD 0)
                                end
                            else
                                 GalOsnma(i).authentic_time(6,j)= GalOsnma(i).data.SVID(ind(k)); %Authentication failed (ADKD 0)
                            end


                        case 4
                            if(GalOsnma(i).data.Outcome(ind(k))<12)&&(GalOsnma(i).data.Outcome(ind(k))>0)

                                GalOsnma(i).authentic_time(5,j)= GalOsnma(i).data.SVID(ind(k));  %Galileo timing authentication (ADKD 4)
                            end

                        case 12
                            if(GalOsnma(i).data.Outcome(ind(k))<12)&&(GalOsnma(i).data.Outcome(ind(k))>0)

                                if(GalOsnma(i).data.SVID(ind(k))==GalOsnma(i).data.PRNA(ind(k)))
                                    GalOsnma(i).authentic_time(1,j)= GalOsnma(i).data.SVID(ind(k)); %Slow MAC self-authentication (ADKD 12)
                                else
                                    GalOsnma(i).authentic_time(2,j)= GalOsnma(i).data.SVID(ind(k)); %Slow MAC cross-authentication (ADKD 12)
                                end
                            end
                      
                        case 99
                             if(GalOsnma(i).data.Gap(ind(k)))
                                  GalOsnma(i).authentic_time(7,j)= GalOsnma(i).data.SVID(ind(k));                                 
                             elseif(GalOsnma(i).data.AllZeros(ind(k)))
                                  GalOsnma(i).authentic_time(9,j)= GalOsnma(i).data.SVID(ind(k));                                 
                             elseif(GalOsnma(i).data.TESLAfail(ind(k)))
                                  GalOsnma(i).authentic_time(8,j)= GalOsnma(i).data.SVID(ind(k));                                 
                             elseif(GalOsnma(i).data.Tagfail(ind(k)))
                                  GalOsnma(i).authentic_time(10,j)= GalOsnma(i).data.SVID(ind(k));   
                             elseif(GalOsnma(i).data.CRC(ind(k)))
                                  GalOsnma(i).authentic_time(13,j)= GalOsnma(i).data.SVID(ind(k));  
                             end
                    end
                end
            end
        end

    end
end
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if(flag_kroot==0) 
    disp('OSNMA Receiver initialization incomplete, Data may be too short');
else
%Time calculation 
gpsLeapSecond=18; receiverTow = zeros(1, length(GalOsnma(i).time_lapse)); time = seconds(zeros(1, length(GalOsnma(i).time_lapse)));
for timeIndex=1:length(GalOsnma(i).time_lapse)
    receiverTow(timeIndex)= floor(GalOsnma(i).time_lapse(timeIndex)); % Modified here to only include the first receiverTOW  
    day = floor(((receiverTow(timeIndex)/60)/60)/24);
    daySub=day*24*3600;
    time(timeIndex)=seconds(receiverTow(timeIndex)-daySub-gpsLeapSecond);
    time.Format = 'hh:mm:ss';
end


% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Extending data received after 30sec to per sec
for i=1:length(GalOsnma)
   for k=1:height(GalOsnma(i).authentic_time) 
       ind=find(~isnan(GalOsnma(i).authentic_time(k,:)));    
       for j=1:length(ind)
            if(k==5)
                end_count=ind(j)+59; %ADKD4 is authenticated for 60sec
                st_count=ind(j)-59;
            else
                end_count=ind(j)+29;
                st_count=ind(j)-29; %Rest is authenticated for 30sec
            end
           if(end_count>length(GalOsnma(i).authentic_time))
               end_count=length(GalOsnma(i).authentic_time);
           end
         
           GalOsnma(i).authentic_time(k,ind(j)+1:end_count)=GalOsnma(i).svID;
       end
   end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Updating Tagfail and failure to authenticate ADKD0
for i=1:length(sat_ID)   
    for j=1:length(GalOsnma(i).authentic_time)         
        %Updating failure to authenticate ADKD0
        if(isnan(GalOsnma(i).authentic_time(10,j)))
            if(((isnan(GalOsnma(i).authentic_time(3,j)))&&~isnan(GalOsnma(i).authentic_time(4,j))))  %If sat is ADKO cross authticated
                GalOsnma(i).authentic_time(6,j)= NaN;
            end
            if(((~isnan(GalOsnma(i).authentic_time(3,j)))&&isnan(GalOsnma(i).authentic_time(4,j))))  %If sat is ADKO self authticated
                 GalOsnma(i).authentic_time(6,j)= NaN;
            end
            if(((isnan(GalOsnma(i).authentic_time(3,j)))&&isnan(GalOsnma(i).authentic_time(4,j))))   %If sat is not ADKO authticated
                     GalOsnma(i).authentic_time(6,j)= sat_ID(i);                %Insufficient data due to intialization or other reasons % If we dont want to seperate it with tag failures
            end
        else
            GalOsnma(i).authentic_time(6,j)= sat_ID(i);                 %ADKOFailedtoAuthenticate 
        end

    end
end 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
time=1:1:length(GalOsnma(i).authentic_time);

figure
for i=1:length(sat_ID)
    markerSize = 50; 
    scatter(time,GalOsnma(i).authentic_time(1,:)-0.25,markerSize,'*','magenta'); %'SlowSelfAuthADKD12'
    hold on; grid on;
    scatter(time,GalOsnma(i).authentic_time(2,:)-0.25,markerSize,'*','yellow'); %'SlowCrossAuthADKD12'
    
    for j=1:length(GalOsnma(i).authentic_time)
        if(~isnan(GalOsnma(i).authentic_time(5,j)))
            GalOsnma(i).authentic_time(5,j)=0;
        end
    end
    scatter(time,GalOsnma(i).authentic_time(5,:),[], [0.5 0.5 0.5],'filled'); %'ConstellAuthADKD4' 
     
    scatter(time,GalOsnma(i).authentic_time(3,:),markerSize,'green'); %'SelfAuthADKD0'
     
    scatter(time,GalOsnma(i).authentic_time(4,:),markerSize,'cyan'); %'CrossAuthADKD0'
     
    % scatter(time,GalOsnma(i).authentic_time(10,:)+0.15,markerSize,'|','red'); %'TagNotVerified'
     
    % scatter(time,GalOsnma(i).authentic_time(7,:)+0.15,markerSize,'|','blue'); %'GapinSubframe'
     
    % scatter(time,GalOsnma(i).authentic_time(8,:)+0.15,markerSize,'*','black'); %'TESLAFail'
     
    % scatter(time,GalOsnma(i).authentic_time(9,:)+0.15,markerSize,'|','black'); %'AllZeros'
     
    scatter(time,GalOsnma(i).authentic_time(6,:)+0.15,markerSize,'r');%'ADKD0authenticationFail'
     
    % scatter(time,GalOsnma(i).authentic_time(13,:)+0.15,markerSize,'|','red');%'CRCFail'
   
end
ylabel('Satellite ID');
xlabel('UTC Time [hh:mm:ss]');
ylim([0 36]); 
legend('SlowSelfAuthADKD12','SlowCrossAuthADKD12','ConstellAuthADKD4','SelfAuthADKD0','CrossAuthADKD0','ADKD0NotAuthenticated');
%legend('SlowSelfAuthADKD12','SlowCrossAuthADKD12','ConstellAuthADKD4','SelfAuthADKD0','CrossAuthADKD0','TagNotVerified','GapinSubframe','TESLAFail','AllZeros','CRCFail');
title('FGI-OSNMA');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

end




